
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/wordotech
    username: root
    password: admin
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true

  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 200MB
      max-request-size: 215MB

aws:
   accessKey: AKIA6CKO5UKLKC6C7YPZ
   secretKey: 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
   region: us-east-1
   s3:
       bucket: wordotech-bucket
