server:
  port: 5000

spring:
  datasource:
    url: jdbc:mysql://awseb-e-taxmgutnmm-stack-awsebrdsdatabase-tt5xbuuwc9kt.cz5ihnkmoddj.ap-south-1.rds.amazonaws.com:3306/wordotech
    username: SubAdminAnshu
    password: Word-Anshu
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true


# For file operations
servlet:
  multipart:
    enabled: true
    file-size-threshold: 2KB
    max-file-size: 200MB
    max-request-size: 215MB

aws:
  accessKey: AKIA6CKO5UKLKC6C7YPZ
  secretKey: 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
  region: us-east-1
  s3:
    bucket: wordotech-bucket
